CREATE DATABASE EXAMPLE_DB;
USE EXAMPLE_DB;

DROP TABLE EXAMPLE;
DROP TABLE HIBERNATE_SEQUENCE;

CREATE TABLE EXAMPLE(
	prime INT PRIMARY KEY AUTO_INCREMENT,
	comment TEXT,
    number INT
);

DELETE FROM EXAMPLE WHERE prime = 1;
SELECT * FROM EXAMPLE;

SELECT * FROM example_db.employee;