server.port=4040
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/example_db?serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=root

# hibernate 오류가 떴을 때 사용
# 서버를 킬 때마다 자동 생성
# spring.jpa.hibernate.ddl-auto=create